version: '3.1'

services:

  postgres:
    image: postgres:12.2
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ril
      POSTGRES_USER: ril 
      POSTGRES_PASSWORD: ril 
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
