import { Mixin } from 'ts-mixer';

import { Entity, Recipe } from '../../_core';
import {
  Actor,
  ActorProps,
  ITimestamps,
  TimestampMixin,
  Timestamps,
} from '../../_shared';
import { OrganizationId } from '../../organizations/domain';
import { BranchId } from './branch-id';

export interface BranchProps extends ActorProps {
  readonly id: BranchId;
  readonly organizationId: OrganizationId;
  readonly timestamps: Timestamps;
}

type AutoGenerated = 'id' | 'timestamps';
const mixins = Mixin(Actor, Entity<BranchId, BranchProps>, TimestampMixin);

export class Branch extends mixins implements ITimestamps {
  get id() {
    return this._props.id;
  }

  get organizationId() {
    return this._props.organizationId;
  }

  public static create(
    props: Omit<Recipe<BranchProps>, AutoGenerated>,
  ): Branch {
    return Branch.rehydrate({
      ...props,
      id: new BranchId(),
      timestamps: new Timestamps(),
    });
  }

  public static rehydrate(props: Recipe<BranchProps>): Branch {
    return new Branch({
      ...Actor.rehydrate(props),
      id: new BranchId(props.id),
      organizationId: new OrganizationId(props.organizationId),
      timestamps: props.timestamps,
    });
  }
}
