import Color from 'color';
import { produce } from 'immer';
import { Mixin } from 'ts-mixer';

import { AggregateRoot, Recipe } from '../../_core';
import {
  ITimestamps,
  TimestampMixin,
  Timestamps,
  TwitterUsername,
  YoutubeChannelId,
} from '../_shared';
import { MediaAttachment } from '../media-attachment';
import { OrganizationId } from '../organization';
import { PerformerDescription } from './performer-description';
import { PerformerId } from './performer-id';
import { PerformerName } from './performer-name';

export type PerformerProps = {
  readonly id: PerformerId;
  readonly name: PerformerName;
  readonly color: Color;
  readonly url: URL | null;
  readonly description: PerformerDescription | null;
  readonly avatar: MediaAttachment | null;
  readonly twitterUsername: TwitterUsername | null;
  readonly youtubeChannelId: YoutubeChannelId | null;
  readonly timestamps: Timestamps;
  readonly organizationId: OrganizationId | null;
};

type AutoGenerated = 'id' | 'timestamps';

const mixins = Mixin(
  AggregateRoot<PerformerId, PerformerProps>,
  TimestampMixin,
);

export class Performer extends mixins implements ITimestamps {
  public get id(): PerformerId {
    return this._props.id;
  }

  public get name(): PerformerName {
    return this._props.name;
  }

  public get color(): Color {
    return this._props.color;
  }

  public get url(): URL | null {
    return this._props.url;
  }

  public get description(): PerformerDescription | null {
    return this._props.description;
  }

  public get avatar(): MediaAttachment | null {
    return this._props.avatar;
  }

  public get twitterUsername(): TwitterUsername | null {
    return this._props.twitterUsername;
  }

  public get youtubeChannelId(): YoutubeChannelId | null {
    return this._props.youtubeChannelId;
  }

  public get organizationId(): OrganizationId | null {
    return this._props.organizationId;
  }

  joinOrganization(organizationId: OrganizationId) {
    const props = produce(this._props, (draft) => {
      draft.organizationId = organizationId;
      draft.timestamps = draft.timestamps.update();
    });
    return new Performer(props);
  }

  setName(name: PerformerName) {
    const props = produce(this._props, (draft) => {
      draft.name = name;
      draft.timestamps = draft.timestamps.update();
    });
    return new Performer(props);
  }

  setDescription(name: PerformerDescription | null) {
    const props = produce(this._props, (draft) => {
      draft.description = name;
      draft.timestamps = draft.timestamps.update();
    });
    return new Performer(props);
  }

  setYoutubeChannelId(id: YoutubeChannelId | null) {
    const props = produce(this._props, (draft) => {
      draft.youtubeChannelId = id;
      draft.timestamps = draft.timestamps.update();
    });
    return new Performer(props);
  }

  setTwitterUsername(username: TwitterUsername | null) {
    const props = produce(this._props, (draft) => {
      draft.twitterUsername = username;
      draft.timestamps = draft.timestamps.update();
    });
    return new Performer(props);
  }

  setColor(color: Color) {
    const props = produce(this._props, (draft) => {
      draft.color = color;
      draft.timestamps = draft.timestamps.update();
    });
    return new Performer(props);
  }

  setUrl(url: URL | null) {
    const props = produce(this._props, (draft) => {
      draft.url = url;
      draft.timestamps = draft.timestamps.update();
    });
    return new Performer(props);
  }

  public static create(props: Omit<Recipe<PerformerProps>, AutoGenerated>) {
    return Performer.rehydrate({
      // ...Actor.create(props),
      ...props,
      id: new PerformerId(),
      timestamps: new Timestamps(),
    });
  }

  public static rehydrate(props: Recipe<PerformerProps>) {
    return new Performer({
      id: new PerformerId(props.id),
      name: new PerformerName(props.name),
      color: props.color,
      description:
        props.description !== null
          ? new PerformerDescription(props.description)
          : null,
      avatar: props.avatar,
      url: props.url,
      youtubeChannelId:
        props.youtubeChannelId !== null
          ? new YoutubeChannelId(props.youtubeChannelId)
          : null,
      twitterUsername:
        props.twitterUsername !== null
          ? new TwitterUsername(props.twitterUsername)
          : null,
      timestamps: props.timestamps,
      organizationId:
        props.organizationId !== null
          ? new OrganizationId(props.organizationId)
          : null,
    });
  }
}
