name: 'CI: api'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
    paths:
      - packages/@neet/vschedule-api-client/**
      - packages/@neet/vschedule-api-spec/**
      - packages/@neet/vschedule-api/**
      - packages/@neet/vschedule-eslint-plugin/**
      - packages/@neet/vschedule-tsconfig/**

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Tokyo'
      DATABASE_URL: mysql://user:password@localhost:3306/test
      YOUTUBE_DATA_API_KEY: ${{ secrets.YOUTUBE_DATA_API_KEY }}
      YOUTUBE_WEBSUB_HMAC_SECRET: test

    services:
      db:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Yarn
        run: |
          yarn workspaces focus @neet/vschedule-api

      - name: Build
        run: |
          yarn workspaces foreach -pR --topological-dev --from @neet/vschedule-api run build

      - name: Tests
        run: |
          yarn workspace @neet/vschedule-api run test

      - name: Codecov
        uses: codecov/codecov-action@v1.0.15
        with:
          flags: api
          token: ${{ secrets.CODECOV_TOKEN }}
