name: 'CI: client'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
    paths:
      - packages/@ril/api-client/**
      - packages/@ril/api-spec/**
      - packages/@ril/client/**
      - packages/@ril/eslint-plugin/**
      - packages/@ril/tsconfig/**

env:
  TZ: 'Asia/Tokyo'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # c.f. https://github.com/vercel/next.js/blob/canary/errors/no-cache.md#github-actions
      - name: Restore Next.js Caches
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/packages/@ril/client.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Yarn
        run: |
          yarn workspaces focus @ril/client

      - name: Build
        run: |
          yarn workspaces foreach -ptR --from @ril/client run build

      - name: Tests
        run: |
          yarn workspace @ril/client run test

      - name: Codecov
        uses: codecov/codecov-action@v1.0.15
        with:
          flags: client
          token: ${{ secrets.CODECOV_TOKEN }}
