# Borrowed from https://www.chromatic.com/docs/github-actions
name: 'CI: Chromatic'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
    paths:
      - packages/@ril/api-client/**
      - packages/@ril/api-spec/**
      - packages/@ril/client/**
      - packages/@ril/eslint-plugin/**
      - packages/@ril/tsconfig/**

jobs:
  chromatic-deployment:
    name: Chromatic Deployment
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Yarn
        run: |
          yarn workspaces focus @ril/client

      - name: Build
        run: |
          yarn workspace @ril/client build-storybook

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          autoAcceptChanges: main
          exitZeroOnChanges: true
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          skip: 'dependabot/**'
          storybookBuildDir: packages/@ril/client/storybook-static
          token: ${{ secrets.GITHUB_TOKEN }}
