# Borrowed from https://www.chromatic.com/docs/github-actions
name: 'CI: Chromatic'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
    paths:
      - packages/@neet/vschedule-api-client/**
      - packages/@neet/vschedule-api-spec/**
      - packages/@neet/vschedule-client/**
      - packages/@neet/vschedule-eslint-plugin/**
      - packages/@neet/vschedule-tsconfig/**

jobs:
  chromatic-deployment:
    name: Chromatic Deployment
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - uses: actions/checkout@v3
        with:
          # https://www.chromatic.com/docs/github-actions#support-for-codeactionscheckoutv2code-and-above
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Yarn
        run: |
          yarn workspaces focus @neet/vschedule-client

      - name: Build
        run: |
          yarn workspace @neet/vschedule-client build-storybook

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          autoAcceptChanges: main
          exitZeroOnChanges: true
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          skip: 'dependabot/**'
          storybookBuildDir: packages/@neet/vschedule-client/storybook-static
          token: ${{ secrets.GITHUB_TOKEN }}
