name: 'CI: client'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
    paths:
      - packages/@neet/vschedule-api-spec/**
      - packages/@neet/vschedule-client/**
      - packages/@neet/vschedule-eslint-plugin/**
      - packages/@neet/vschedule-tsconfig/**

env:
  TZ: 'Asia/Tokyo'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: yarn

      # https://nextjs.org/docs/advanced-features/ci-build-caching#github-actions
      - name: Restore Next.js Caches
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/packages/@neet/vschedule-client/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-

      - name: Yarn
        run: |
          yarn workspaces focus @neet/vschedule-client

      - name: Build
        run: |
          yarn workspaces foreach -ptR --from @neet/vschedule-client run build

      - name: Tests
        run: |
          yarn workspace @neet/vschedule-client run test

      - name: Codecov
        uses: codecov/codecov-action@v1.0.15
        with:
          flags: client
          token: ${{ secrets.CODECOV_TOKEN }}
