name: 'CI: core'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
    paths:
      - packages/@ril/core/**
      - packages/@ril/eslint-plugin/**
      - packages/@ril/tsconfig/**

env:
  TZ: 'Asia/Tokyo'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # https://dev.to/mpocock1/how-to-cache-nodemodules-in-github-actions-with-yarn-24e
      - name: Restore Yarn Caches
        uses: actions/cache@v2.1.7
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-core-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn
        run: |
          yarn workspaces focus @ril/core

      - name: Build
        run: |
          yarn workspaces foreach -ptR --from @ril/core run build

      - name: Tests
        run: |
          yarn workspace @ril/core run test

      - name: Codecov
        uses: codecov/codecov-action@v1.0.15
        with:
          flags: core
          token: ${{ secrets.CODECOV_TOKEN }}
